-- ============================================================================
-- 14 · Datos preliminares de muestra de fauna (Anexo. Fauna línea base.xlsx)
-- Aves, herpetos (reptiles) y mamíferos por cobertura, con abundancia.
-- Idempotente: borra la muestra previa antes de reinsertar.
-- ============================================================================
SET search_path TO eco_restauracion, public;

ALTER TABLE eco_restauracion.fauna_observaciones ADD COLUMN IF NOT EXISTS grupo TEXT;

DELETE FROM eco_restauracion.fauna_observaciones WHERE observacion = 'Línea base (muestra)';

INSERT INTO eco_restauracion.fauna_observaciones
  (grupo, nombre_cientifico, nombre_comun, cobertura_vegetal, n_individuos, observacion)
VALUES
('aves','Leptotila verreauxi','','Vegetación secundaria',3,'Línea base (muestra)'),
('aves','Icterus nigrogularis','','Mosaico de cultivos',2,'Línea base (muestra)'),
('aves','Theristicus caudatus','','Bosque denso',1,'Línea base (muestra)'),
('aves','Crotophaga major','','Bosque ripario',4,'Línea base (muestra)'),
('aves','Columbina squammata','','Tierras desnudas',2,'Línea base (muestra)'),
('aves','Columbina squammata','','Tierras desnudas',2,'Línea base (muestra)'),
('aves','Columbina squammata','','Tierras desnudas',4,'Línea base (muestra)'),
('aves','Tapera naevia','','Vegetación secundaria',1,'Línea base (muestra)'),
('aves','Ortalis garrula','','Mosaico de cultivos',4,'Línea base (muestra)'),
('aves','Rupornis magnirostris','','Bosque denso',2,'Línea base (muestra)'),
('aves','Crotophaga ani','','Bosque ripario',8,'Línea base (muestra)'),
('aves','Leptotila verreauxi','','Tierras desnudas',4,'Línea base (muestra)'),
('aves','Leptotila verreauxi','','Tierras desnudas',4,'Línea base (muestra)'),
('aves','Leptotila verreauxi','','Tierras desnudas',5,'Línea base (muestra)'),
('aves','Piaya cayana','','Vegetación secundaria',2,'Línea base (muestra)'),
('aves','Saltator coerulescens','','Mosaico de cultivos',2,'Línea base (muestra)'),
('aves','Formicivora intermedia','','Bosque denso',1,'Línea base (muestra)'),
('aves','Crotophaga sulcirostris','','Bosque ripario',5,'Línea base (muestra)'),
('aves','Crotophaga ani','','Tierras desnudas',3,'Línea base (muestra)'),
('aves','Crotophaga ani','','Tierras desnudas',3,'Línea base (muestra)'),
('aves','Crotophaga ani','','Tierras desnudas',5,'Línea base (muestra)'),
('aves','Melanerpes rubricapillus','','Vegetación secundaria',3,'Línea base (muestra)'),
('aves','Coragyps atratus','','Mosaico de cultivos',2,'Línea base (muestra)'),
('aves','Chiroxiphia lanceolata','','Bosque denso',1,'Línea base (muestra)'),
('aves','Vanellus chilensis','','Bosque ripario',3,'Línea base (muestra)'),
('aves','Coragyps atratus','','Tierras desnudas',6,'Línea base (muestra)'),
('aves','Coragyps atratus','','Tierras desnudas',6,'Línea base (muestra)'),
('aves','Coragyps atratus','','Tierras desnudas',4,'Línea base (muestra)'),
('aves','Dryocopus lineatus','','Vegetación secundaria',2,'Línea base (muestra)'),
('aves','Cathartes aura','','Mosaico de cultivos',3,'Línea base (muestra)'),
('aves','Pachyramphus polychopterus','','Bosque denso',2,'Línea base (muestra)'),
('aves','Phalacrocorax brasilianus','','Bosque ripario',5,'Línea base (muestra)'),
('aves','Cathartes aura','','Tierras desnudas',3,'Línea base (muestra)'),
('aves','Cathartes aura','','Tierras desnudas',3,'Línea base (muestra)'),
('aves','Cathartes aura','','Tierras desnudas',5,'Línea base (muestra)'),
('aves','Camptostoma obsoletum','','Vegetación secundaria',1,'Línea base (muestra)'),
('aves','Tolmomyias sulphurescens','','Bosque denso',1,'Línea base (muestra)'),
('aves','Ardea alba','','Bosque ripario',6,'Línea base (muestra)'),
('aves','Buteogallus meridionalis','','Tierras desnudas',2,'Línea base (muestra)'),
('aves','Buteogallus meridionalis','','Tierras desnudas',2,'Línea base (muestra)'),
('aves','Buteogallus meridionalis','','Tierras desnudas',2,'Línea base (muestra)'),
('aves','Capsiempis flaveola','','Vegetación secundaria',1,'Línea base (muestra)'),
('aves','Thryophilus rufalbus','','Bosque denso',1,'Línea base (muestra)'),
('aves','Egretta thula','','Bosque ripario',3,'Línea base (muestra)'),
('aves','Rupornis magnirostris','','Tierras desnudas',4,'Línea base (muestra)'),
('aves','Rupornis magnirostris','','Tierras desnudas',4,'Línea base (muestra)'),
('aves','Rupornis magnirostris','','Tierras desnudas',4,'Línea base (muestra)'),
('aves','Pitangus sulphuratus','','Vegetación secundaria',3,'Línea base (muestra)'),
('aves','Coereba flaveola','','Bosque denso',1,'Línea base (muestra)'),
('aves','Egretta caerulea','','Bosque ripario',1,'Línea base (muestra)'),
('aves','Caracara plancus','','Tierras desnudas',2,'Línea base (muestra)'),
('aves','Caracara plancus','','Tierras desnudas',2,'Línea base (muestra)'),
('aves','Daptrius chimachima','','Tierras desnudas',1,'Línea base (muestra)'),
('aves','Myiozetetes cayanensis','','Vegetación secundaria',2,'Línea base (muestra)'),
('aves','Colaptes punctigula','','Bosque denso',2,'Línea base (muestra)'),
('aves','Butorides virescens','','Bosque ripario',1,'Línea base (muestra)'),
('aves','Daptrius chimachima','','Tierras desnudas',6,'Línea base (muestra)'),
('aves','Daptrius chimachima','','Tierras desnudas',6,'Línea base (muestra)'),
('aves','Eupsittula pertinax','','Tierras desnudas',10,'Línea base (muestra)'),
('aves','Cyanocorax affinis','','Vegetación secundaria',7,'Línea base (muestra)'),
('aves','Ortalis garrula','','Bosque denso',3,'Línea base (muestra)'),
('aves','Phimosus infuscatus','','Bosque ripario',2,'Línea base (muestra)'),
('aves','Eupsittula pertinax','','Tierras desnudas',10,'Línea base (muestra)'),
('aves','Eupsittula pertinax','','Tierras desnudas',10,'Línea base (muestra)'),
('aves','Pitangus sulphuratus','','Tierras desnudas',3,'Línea base (muestra)'),
('aves','Campylorhynchus griseus','','Vegetación secundaria',4,'Línea base (muestra)'),
('aves','Cyanocorax affinis','','Bosque denso',5,'Línea base (muestra)'),
('aves','Coragyps atratus','','Bosque ripario',5,'Línea base (muestra)'),
('aves','Pitangus sulphuratus','','Tierras desnudas',4,'Línea base (muestra)'),
('aves','Pitangus sulphuratus','','Tierras desnudas',4,'Línea base (muestra)'),
('aves','Tyrannus melancholicus','','Tierras desnudas',7,'Línea base (muestra)'),
('aves','Cantorchilus leucotis','','Vegetación secundaria',1,'Línea base (muestra)'),
('aves','Cathartes aura','','Bosque ripario',3,'Línea base (muestra)'),
('aves','Tyrannus melancholicus','','Tierras desnudas',2,'Línea base (muestra)'),
('aves','Tyrannus melancholicus','','Tierras desnudas',2,'Línea base (muestra)'),
('aves','Cyanocorax affinis','','Tierras desnudas',6,'Línea base (muestra)'),
('aves','Icterus nigrogularis','','Vegetación secundaria',2,'Línea base (muestra)'),
('aves','Megaceryle torquata','','Bosque ripario',6,'Línea base (muestra)'),
('aves','Cyanocorax affinis','','Tierras desnudas',7,'Línea base (muestra)'),
('aves','Cyanocorax affinis','','Tierras desnudas',7,'Línea base (muestra)'),
('aves','Ortalis garrula','','Tierras desnudas',9,'Línea base (muestra)'),
('aves','Protonotaria citrea','','Vegetación secundaria',1,'Línea base (muestra)'),
('aves','Pandion haliaetus','','Bosque ripario',2,'Línea base (muestra)'),
('aves','Volatinia jacarina','','Tierras desnudas',8,'Línea base (muestra)'),
('aves','Volatinia jacarina','','Tierras desnudas',8,'Línea base (muestra)'),
('aves','Ortalis garrula','','Tierras desnudas',9,'Línea base (muestra)'),
('aves','Ortalis garrula','','Tierras desnudas',9,'Línea base (muestra)'),
('aves','Columbina talpacoti','','Tierras desnudas',7,'Línea base (muestra)'),
('aves','Columbina talpacoti','','Tierras desnudas',7,'Línea base (muestra)'),
('reptiles','Anolis gaigei','','Vegetación secundaria',4,'Línea base (muestra)'),
('reptiles','Anolis auratus','','Vegetación secundaria',5,'Línea base (muestra)'),
('reptiles','Gonatodes albogularis','','Vegetación secundaria',1,'Línea base (muestra)'),
('reptiles','Cnemidophorus lemniscatus','','Vegetación secundaria',3,'Línea base (muestra)'),
('reptiles','Gonatodes albogularis','','Vegetación secundaria',4,'Línea base (muestra)'),
('reptiles','Erythrolamprus bizonus','','Vegetación secundaria',5,'Línea base (muestra)'),
('reptiles','Cnemidophorus lemniscatus','','Mosaico de cultivos',3,'Línea base (muestra)'),
('reptiles','Anolis auratus','','Mosaico de cultivos',4,'Línea base (muestra)'),
('reptiles','Ameiva praesignis','','Bosque denso',4,'Línea base (muestra)'),
('reptiles','Anolis auratus','','Bosque denso',3,'Línea base (muestra)'),
('reptiles','Ameiva praesignis','','Bosque ripario',2,'Línea base (muestra)'),
('reptiles','Rhinella humboldti','','Bosque ripario',1,'Línea base (muestra)'),
('reptiles','Anolis auratus','','Bosque ripario',2,'Línea base (muestra)'),
('reptiles','Erythrolamprus bizonus','','Tierras desnudas',1,'Línea base (muestra)'),
('reptiles','Anolis auratus','','Tierras desnudas',3,'Línea base (muestra)'),
('reptiles','Erythrolamprus bizonus','','Tierras desnudas',1,'Línea base (muestra)'),
('reptiles','Bothrops asper','','Tierras desnudas',2,'Línea base (muestra)'),
('mamiferos','Alouatta seniculus','Mono aullador','Vegetación secundaria',5,'Línea base (muestra)'),
('mamiferos','Syntheosciurus granatensis','Ardilla','Vegetación secundaria',4,'Línea base (muestra)'),
('mamiferos','Dasyprocta punctata','Ñeque','Vegetación secundaria',3,'Línea base (muestra)'),
('mamiferos','Cerdocyon thous','Zorro perro','Vegetación secundaria',2,'Línea base (muestra)'),
('mamiferos','Passalites sanctaemartae','Venado','Vegetación secundaria',1,'Línea base (muestra)'),
('mamiferos','Leopardus pardalis','Ocelote','Vegetación secundaria',2,'Línea base (muestra)'),
('mamiferos','Eira barbara','Tayra','Vegetación secundaria',1,'Línea base (muestra)'),
('mamiferos','Conepatus semistratus','Zorrillo','Vegetación secundaria',1,'Línea base (muestra)'),
('mamiferos','Procyon cancrivorus','Mapache','Mosaico de cultivos',1,'Línea base (muestra)'),
('mamiferos','Cerdocyon thous','Zorro perro','Mosaico de cultivos',3,'Línea base (muestra)'),
('mamiferos','Sylvigalus floridanus','Conejo','Mosaico de cultivos',2,'Línea base (muestra)'),
('mamiferos','Syntheosciurus granatensis','Ardilla','Bosque denso',2,'Línea base (muestra)'),
('mamiferos','Tamandua mexicana','Oso hormiguero','Bosque denso',1,'Línea base (muestra)');

SELECT 'Migración 14 (muestra de fauna, 119 registros) aplicada' AS mensaje;
